export type pitanje = {
  i: number;
  q: string;
  a: string;
  b: string;
  c?: string;
  d?: string;
  correct: string[];
};
export const pitanja: pitanje[] = [
  {
    i: 1,
    q: "Koja je maksimalna dozvoljena brzina kretanja vozila u naseljenom mjestu, ako saobraćajnim znakom nije drugačije određeno?",
    a: "40 km/h",
    b: "50 km/h",
    c: "60 km/h",
    correct: ["b"],
  },
  {
    i: 2,
    q: "Šta označava crveno svjetlo na semaforu?",
    a: "Zabranjen prolaz",
    b: "Slobodan prolaz uz oprez",
    c: "Obavezno smanjenje brzine",
    correct: ["a", "b"],
  },
  {
    i: 3,
    q: "Vozilo hitne pomoći sa upaljenim plavim rotacionim svjetlom ima prvenstvo prolaza u odnosu na sva druga vozila osim:",
    a: "Vozila policije",
    b: "Vozila pod pratnjom",
    c: "Tramvaja",
    correct: ["b"],
  },
  {
    i: 4,
    q: "Dozvoljena količina alkohola u krvi za vozače početnike (do 21 godine ili 2 godine iskustva) iznosi:",
    a: "0.3 g/kg",
    b: "0.5 g/kg",
    c: "0.0 g/kg",
    correct: ["c"],
  },
  {
    i: 5,
    q: "Kada je vozač dužan da upali dnevna ili kratka svjetla na vozilu?",
    a: "Samo noću",
    b: "Samo u uslovima smanjene vidljivosti",
    c: "Uvijek, i danju i noću",
    correct: ["c"],
  },
  // {
  //   i: 6,
  //   q: "Šta vozač mora uraditi prije skretanja ulijevo?",
  //   a: "Samo usporiti",
  //   b: "Upaliti lijevi pokazivač pravca i uvjeriti se da radnju može izvršiti bezbjedno",
  //   c: "Samo zatrubiti",
  //   correct: ["b"],
  // },
  // {
  //   i: 7,
  //   q: "Znak 'Stop' (osmogougaoni crveni znak) obavezuje vozača da:",
  //   a: "Uspori i prođe ako nema nikoga",
  //   b: "Obavezno zaustavi vozilo na liniji zaustavljanja ili pregledu raskrsnice",
  //   c: "Samo blica drugim vozačima",
  //   correct: ["b"],
  // },
  // {
  //   i: 8,
  //   q: "Na autoputu je zabranjeno polukružno okretanje i kretanje unazad.",
  //   a: "Tačno",
  //   b: "Netačno",
  //   correct: ["a"],
  // },
  // {
  //   i: 9,
  //   q: "Koji od navedenih faktora najviše produžava put kočenja?",
  //   a: "Muzika u vozilu",
  //   b: "Mokar i klizav kolovoz",
  //   c: "Upaljena klima",
  //   correct: ["b"],
  // },
  // {
  //   i: 10,
  //   q: "Kada se smije preticati drugo vozilo sa desne strane?",
  //   a: "Kada se vozilo ispred isključuje ulijevo, a ima dovoljno prostora desno",
  //   b: "Nikada",
  //   c: "Kada je gužva u saobraćaju",
  //   correct: ["a"],
  // },
  // {
  //   i: 11,
  //   q: "Šta znači žuto svjetlo na semaforu upaljeno istovremeno sa crvenim?",
  //   a: "Spremanje za polazak, uskoro se pali zeleno",
  //   b: "Obavezno kočenje",
  //   c: "Kraj zabrane prolaza",
  //   correct: ["a"],
  // },
  // {
  //   i: 12,
  //   q: "Na kojem rastojanju od mjesta saobraćajne nezgode se postavlja sigurnosni trougao van naselja?",
  //   a: "10 metara",
  //   b: "50 metara",
  //   c: "100 metara",
  //   correct: ["b"],
  // },
  // {
  //   i: 13,
  //   q: "Koja je uloga ABS sistema na vozilu?",
  //   a: "Smanjenje potrošnje goriva",
  //   b: "Sprečavanje blokiranja točkova prilikom naglog kočenja",
  //   c: "Brže startovanje motora",
  //   correct: ["b"],
  // },
  // {
  //   i: 14,
  //   q: "Puna uzdužna linija na kolovozu znači:",
  //   a: "Dozvoljeno preticanje",
  //   b: "Zabranjen prelazak vozila preko te linije",
  //   c: "Oznaka za parking",
  //   correct: ["b"],
  // },
  // {
  //   i: 15,
  //   q: "Vozač koji se uključuje sa sporednog puta na glavni dužan je da:",
  //   a: "Ubrza da ne ometa druge",
  //   b: "Ustupi prvenstvo svim vozilima na glavnom putu",
  //   c: "Samo zatrubi",
  //   correct: ["b"],
  // },
  // {
  //   i: 16,
  //   q: "Šta označava znak u obliku obrnutog trougla (bijela osnova, crveni rub)?",
  //   a: "Zabrana prolaza",
  //   b: "Raskrsnica sa putem sa prvenstvom prolaza",
  //   c: "Opasnost na putu",
  //   correct: ["b"],
  // },
  // {
  //   i: 17,
  //   q: "Kada se koristi sirena u naseljenom mjestu?",
  //   a: "Za pozdravljanje prijatelja",
  //   b: "Samo u slučaju neposredne opasnosti",
  //   c: "Kada je pješak na trotoaru",
  //   correct: ["b"],
  // },
  // {
  //   i: 18,
  //   q: "Da li pješak smije prelaziti kolovoz van pješačkog prelaza ako je isti udaljen više od 100 metara?",
  //   a: "Da, uz maksimalan oprez",
  //   b: "Ne, nikada",
  //   correct: ["a"],
  // },
  // {
  //   i: 19,
  //   q: "Koji je minimalni dozvoljeni profil gume (šara) za ljetne gume na putničkom automobilu?",
  //   a: "1.0 mm",
  //   b: "1.6 mm",
  //   c: "4.0 mm",
  //   correct: ["b"],
  // },
  // {
  //   i: 20,
  //   q: "U raskrsnici bez znakova, ko ima prvenstvo?",
  //   a: "Vozilo koje ide pravo",
  //   b: "Vozilo koje dolazi sa desne strane",
  //   c: "Veće vozilo",
  //   d: "Vozilo koje se brže kreće",
  //   correct: ["b"],
  // },
];
