[
  {
    i: 1,
    q: "Vozač je:",
    a: "svako lice koje se u saobraćaju na putu nalazi u vozilu",
    b: "lice koje na putu upravlja vozilom",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 2,
    q: "Da li je vozač motocikla dužan nositi zaštitnu kacigu za vrijeme vožnje na putu?",
    a: "dužan je nositi samo zaštitne naočale",
    b: "da",
    c: "ne",
    category: ["A"],
    correct: ["b"],
  },
  {
    i: 3,
    q: "Kako se naziva uzdužni dio kolovoza namijenjen za saobraćaj vozila u jednom smjeru sa jednom ili više saobraćajnih traka?",
    a: "kolovozna traka",
    b: "kolovoz",
    c: "saobraćajna traka",
    category: ["A", "B", "C", "D", "T"],
    correct: ["c"],
  },
  {
    i: 4,
    q: "Preglednost podrazumijeva:",
    a: "prostor koji učesnik u saobraćaju može da vidi sa mjesta na kojem se nalazi",
    b: "mjesto na raskrsnici sa kojeg vozač vidi ulijevo i desno najmanje 25 m",
    c: "mjesto na raskrsnici sa kojeg vozač vidi ulijevo najmanje 25 m",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 5,
    q: "Stiker-naljepnica je:",
    a: "dokaz o izvršenom tehničkom pregledu",
    b: "dokaz o plaćenoj putarini",
    c: "dokaz o izvršenoj registraciji vozila",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 6,
    q: "Koliko važi registracija vozila čija zapremina motora ne prelazi 50 ccm?",
    a: "nije vremenski ograničena",
    b: "jednu godinu",
    c: "dvije godine",
    category: ["A"],
    correct: ["b"],
  },
  {
    i: 7,
    q: "Projektovanjem i gradnjom novih javnih puteva mora se obezbijediti osovinsko opterećenje od:",
    a: "najmanje 10 t po osovini",
    b: "najmanje 11,5 t po osovini",
    c: "najmanje 11 t po osovini",
    category: ["B", "C", "D"],
    correct: ["b"],
  },
  {
    i: 8,
    q: "Iznad kolovoza javnog puta mora postojati slobodan prostor u visini od najmanje:",
    a: "4,5 m",
    b: "4 m",
    c: "6 m",
    category: ["A", "B", "C", "D"],
    correct: ["a"],
  },
  {
    i: 9,
    q: "Šta utiče na produženje puta kočenja?",
    a: "mokar kolovoz",
    b: "suv kolovoz",
    c: "opterećenje vozila",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "c"],
  },
  {
    i: 10,
    q: "Najveća dozvoljena brzina za motorno vozilo koje vuče laku prikolicu je:",
    a: "60 km/h",
    b: "80 km/h",
    c: "90 km/h",
    category: ["B", "C"],
    correct: ["b"],
  },
  {
    i: 11,
    q: "Novoproizvedena vozila se nakon prve registracije prvi put vode na tehnički pregled:",
    a: "nakon 36 mjeseci",
    b: "nakon 12 mjeseci",
    c: "nakon 24 mjeseca",
    category: ["A", "B", "C", "D", "T"],
    correct: ["c"],
  },
  {
    i: 12,
    q: "Kako djeca najčešće reaguju u saobraćaju?",
    a: "razumno i staloženo",
    b: "u skladu sa propisima",
    c: "spontano i nepredvidivo",
    category: ["A", "B", "C", "D", "T"],
    correct: ["c"],
  },
  {
    i: 13,
    q: "Kako vozač može smanjiti saobraćajni rizik?",
    a: "agresivnom vožnjom",
    b: "poštovanjem saobraćajnih pravila",
    c: "defanzivnom vožnjom",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b", "c"],
  },
  {
    i: 14,
    q: "Pomoću užeta ne smije se vući vozilo koje ima neispravne:",
    a: "uređaje za osvjetljavanje",
    b: "uređaje za zaustavljanje",
    c: "uređaje za upravljanje",
    category: ["B", "C", "T"],
    correct: ["b", "c"],
  },
  {
    i: 15,
    q: "Ljekarsko uvjerenje o zdravstvenoj sposobnosti važi:",
    a: "12 mjeseci",
    b: "6 mjeseci",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 16,
    q: "Krutom vezom ne smije se vući vozilo:",
    a: "koje ima ispravan uređaj za upravljanje",
    b: "koje je teže od vučnog vozila ako mu je neispravna pomoćna kočnica",
    category: ["B", "C", "T"],
    correct: ["b"],
  },
  {
    i: 17,
    q: "Zaustavljanje vozila je prekid kretanja do:",
    a: "15 minuta",
    b: "5 minuta",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 18,
    q: "Pješak je:",
    a: "lice koje se vozi na koturaljkama",
    b: "lice koje upravlja ili se prevozi u vozilu",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 19,
    q: "Put sa jednosmjernim saobraćajem ima:",
    a: "dvije kolovozne trake",
    b: "jednu kolovoznu traku",
    c: "više kolovoznih traka",
    category: ["A", "B", "C", "D", "T"],
    correct: ["c"],
  },
  {
    i: 20,
    q: "Kratko svjetlo na biciklu i mopedu mora osvjetljavati put:",
    a: "od 10 do 35 m",
    b: "od 10 do 50 m",
    category: ["A"],
    correct: ["a"],
  },
];
[
  {
    i: 21,
    q: "Zaustavljanje vozila na putu je zabranjeno:",
    a: "na obilježenom pješačkom prelazu",
    b: "ispred ulaza u dvorište",
    c: "na parking prostoru",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 22,
    q: "Preticanje je zabranjeno:",
    a: "na raskrsnici",
    b: "na putu sa prvenstvom prolaza",
    c: "na dijelu puta sa isprekidanom linijom",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 23,
    q: "Vozač je dužan obratiti posebnu pažnju na pješake:",
    a: "u blizini škola i vrtića",
    b: "na autoputu",
    c: "samo noću",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 24,
    q: "Vozač ne smije upravljati vozilom ako je pod dejstvom:",
    a: "alkohola",
    b: "opojnih droga",
    c: "lijekova koji utiču na sposobnost vožnje",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "b", "c"],
  },
  {
    i: 25,
    q: "U noćnim uslovima vožnje vozač je dužan koristiti:",
    a: "duga svjetla",
    b: "kratka svjetla",
    c: "svjetla za maglu",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 26,
    q: "Saobraćajna traka je:",
    a: "uzdužni dio kolovoza za kretanje vozila u jednom redu",
    b: "dio puta za pješake",
    c: "dio trotoara",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 27,
    q: "Vozač mora prilagoditi brzinu kretanja:",
    a: "stanju puta",
    b: "vidljivosti",
    c: "saobraćajnim uslovima",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "b", "c"],
  },
  {
    i: 28,
    q: "Zaustavni put vozila zavisi od:",
    a: "brzine kretanja",
    b: "stanja kolovoza",
    c: "reakcionog vremena vozača",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "b", "c"],
  },
  {
    i: 29,
    q: "Pješak je dužan prelaziti kolovoz:",
    a: "van obilježenog prelaza",
    b: "na obilježenom pješačkom prelazu",
    c: "bilo gdje",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 30,
    q: "Vozač koji skreće ulijevo dužan je propustiti:",
    a: "vozila iz suprotnog smjera",
    b: "vozila iza sebe",
    c: "pješake na trotoaru",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 31,
    q: "Saobraćajni znakovi imaju prednost u odnosu na:",
    a: "svjetlosne znakove",
    b: "oznake na kolovozu",
    c: "pravila prvenstva",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b", "c"],
  },
  {
    i: 32,
    q: "Žuto trepćuće svjetlo na semaforu znači:",
    a: "zabranu prolaska",
    b: "oprez i poštovanje znakova",
    c: "slobodan prolaz",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 33,
    q: "Vozač je dužan uključiti pokazivač pravca:",
    a: "prije promjene saobraćajne trake",
    b: "nakon promjene trake",
    c: "samo na raskrsnici",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 34,
    q: "Vozilo mora imati ispravne:",
    a: "uređaje za kočenje",
    b: "svjetlosne uređaje",
    c: "uređaje za upravljanje",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "b", "c"],
  },
  {
    i: 35,
    q: "Na autoputu je zabranjeno:",
    a: "kretanje pješaka",
    b: "kretanje biciklista",
    c: "kretanje mopeda",
    category: ["B", "C", "D"],
    correct: ["a", "b", "c"],
  },
  {
    i: 36,
    q: "Vozač smije koristiti mobilni telefon:",
    a: "tokom vožnje",
    b: "uz hands-free uređaj",
    c: "u zoni škole",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 37,
    q: "Pojas bezbjednosti mora koristiti:",
    a: "vozač",
    b: "suvozač",
    c: "putnici",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a", "b", "c"],
  },
  {
    i: 38,
    q: "Djeca se u vozilu moraju prevoziti:",
    a: "na prednjem sjedištu",
    b: "u sigurnosnoj sjedalici",
    c: "bez posebne zaštite",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
  {
    i: 39,
    q: "Vozač je dužan pomoći povrijeđenom u saobraćajnoj nezgodi:",
    a: "uvijek",
    b: "samo ako je kriv",
    c: "samo ako ima vremena",
    category: ["A", "B", "C", "D", "T"],
    correct: ["a"],
  },
  {
    i: 40,
    q: "U naselju najveća dozvoljena brzina je:",
    a: "40 km/h",
    b: "50 km/h",
    c: "60 km/h",
    category: ["A", "B", "C", "D", "T"],
    correct: ["b"],
  },
];
